### ISSUE TITLE
NPM package names can't contain ~

### ISSUE THREAD

**Issue by MathieuAA** [dword-design/package-name-regex#18]
You can see the logged error `Sorry, name can no longer contain special characters ("~'!()*").` when doing an NPM init. They actually use [this](https://github.com/npm/validate-npm-package-name) package to check.

**Comment by dword-design** [comment]
@MathieuAA Thanks for the investigation! Are you up for writing a PR with an adjusted regex and some new tests?

**Comment by MathieuAA** [comment]
Yes. Maybe not today, but first thing tomorrow! There are other rules too, I'll create a PR including every if you want

**Comment by dword-design** [comment]
@MathieuAA sure as you like
